eclipse-equinox/p2

- bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.repository/pom.xml
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/provisional/p2/repository/DefaultPGPPublicKeyService.java
Subdirectories must be created as well
> Fix #13 - NoSuchFileException using a custom keyserver

- bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/MirrorApplication.java
Fix https://github.com/eclipse-equinox/p2/issues/60
> Add new MirrorApplication#createSlicer to allow extension/customization

- features/org.eclipse.equinox.p2.core.feature/forceQualifierUpdate.txt
> Touch o.e.equinox.p2.core feature for bouncycastle qualifier update in

- bundles/org.eclipse.equinox.simpleconfigurator/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.simpleconfigurator/src/org/eclipse/equinox/internal/simpleconfigurator/ConfigApplier.java
> Issue #90 - Avoid refreshing simple configurator fragments

- features/org.eclipse.equinox.p2.core.feature/feature.xml
> Use bouncycastle from Maven Central

- bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/CertificateChecker.java
https://github.com/eclipse-equinox/p2/issues/121
> WIP This is essentially a no-op commit to see if any tests current fail

- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/CertificateChecker.java
Fix the logic to properly test for trusted certificate signature and
then trusted PGP signature per artifact
https://github.com/eclipse-equinox/p2/issues/121
> Check for PGP signatures even if the artifact is jar signed

- bundles/org.eclipse.equinox.frameworkadmin/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.frameworkadmin/src/org/eclipse/equinox/frameworkadmin/package.html
- bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/package.html
- bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/spi/package.html
- bundles/org.eclipse.equinox.p2.director/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.director/src/org/eclipse/equinox/p2/planner/package.html
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/package.html
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/query/package.html
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/spi/package.html
- bundles/org.eclipse.equinox.p2.metadata/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/expression/package.html
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/index/package.html
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/package.html
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/IMatchQuery.java
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/package.html
- bundles/org.eclipse.equinox.p2.operations/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/package.html
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/package.html
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/spi/ArtifactRepositoryFactory.java
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/spi/package.html
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/package.html
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/spi/AbstractMetadataRepository.java
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/package.html
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/spi/package.html
- bundles/org.eclipse.equinox.p2.touchpoint.eclipse/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/p2/touchpoint/eclipse/query/package.html
- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/p2/ui/package.html
As found by Java 17 javadoc tool.
Needed by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/482
> Fix Javadoc warnings and errors.

- .mvn/extensions.xml
@akurtakov any objections to upgrade to 3.0.0 here?
> Use Tycho 3.0.0 build extension

- bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/provisional/p2/repository/DefaultPGPPublicKeyService.java
Fixes https://github.com/eclipse-equinox/p2/issues/153
> Fix compile error using org.bouncycastle.bcpg_1.72.0.v20221013-1810

- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/AbstractAntProvisioningTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/AbstractProvisioningTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/ant/MirrorTaskTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/ChecksumUtilitiesTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/ChecksumVerifierTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/CompositeArtifactRepositoryTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/MD5Tests.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/mirror/ArtifactMirrorApplicationTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/mirror/NewMirrorApplicationArtifactTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/ChecksumGenerationTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/MD5GenerationTest.java
General cleanup and moving away of legacy properties.
> Tests modernization

- bundles/org.eclipse.equinox.p2.console/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.directorywatcher/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.discovery/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.garbagecollector/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.ui.admin/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.updatechecker/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.simpleconfigurator/META-INF/MANIFEST.MF
- features/org.eclipse.equinox.p2.discovery.feature/feature.xml
Needed for resigning for
eclipse-platform/eclipse.platform.releng.aggregator#661
> Version bumps for 4.26 stream

- bundles/org.eclipse.equinox.p2.jarprocessor/META-INF/MANIFEST.MF
- features/org.eclipse.equinox.p2.core.feature/feature.xml
- features/org.eclipse.equinox.p2.extras.feature/feature.xml
- features/org.eclipse.equinox.p2.rcp.feature/feature.xml
- features/org.eclipse.equinox.p2.sdk/feature.xml
- features/org.eclipse.equinox.p2.user.ui/feature.xml
- features/org.eclipse.equinox.server.p2/feature.xml
Version bump for new build. Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/729
> Comparator issues in I20221130-1800

- bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
Fix https://github.com/eclipse-equinox/p2/issues/184
> SimpleArtifactRepository should work will null progress monitor

- bundles/org.eclipse.equinox.p2.publisher/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/AbstractPublisherApplication.java
Fix https://github.com/eclipse-equinox/p2/issues/140
> AbstractPublisherApplication#setupAgent should be protected

- bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepositoryIO.java
Fix https://github.com/eclipse-equinox/p2/issues/124
> SimpleArtifactRepositoryIO#read do not set the location on the parsed repository

- bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/AbstractApplication.java
Fix https://github.com/eclipse-equinox/p2/issues/152
> Add missing null check in AbstractApplication

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/MirrorSelector.java
Fix https://github.com/eclipse-equinox/p2/issues/133
> Improve the error reporting when processing mirrors URL

- features/org.eclipse.equinox.p2.core.feature/forceQualifierUpdate.txt
Needed by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/761
> Touch features

- bundles/org.eclipse.equinox.p2.publisher.eclipse/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
Fix https://github.com/eclipse-equinox/p2/issues/100
> ProductFile should extract the locating of the instance area to a method to allow overrides by extenders

- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/RepositoryNameAndLocationDialog.java
Encourages users to specify a secure repository.
Fixes #209
Signed-off-by: Andrew Johnson <andrew_johnson@uk.ibm.com>
> Suggest https:// not http:// for new repository

- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/Bug351944.java
This test has been added due to some critical performance issue but it doesn't fit current infrastructure that can "sleep" at any point. This patch simply reduces work in measured times in order to reduce chances that the sleep happens there aka "fail less often" Seen in https://download.eclipse.org/eclipse/downloads/drops4/I20230127-1800/testresults/html/org.eclipse.equinox.p2.tests_ep427I-unit-cen64-gtk3-java19_linux.gtk.x86_64_19.html
> Simplify unstable Bug351944 test

- pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916
> POM and product version changes for 4.28 release

- bundles/org.eclipse.equinox.p2.jarprocessor/forceQualifierUpdate.txt
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/947
> Comparator errors in I20230307-0840

- bundles/org.eclipse.equinox.p2.jarprocessor/META-INF/MANIFEST.MF
- features/org.eclipse.equinox.p2.core.feature/feature.xml
- features/org.eclipse.equinox.p2.extras.feature/feature.xml
- features/org.eclipse.equinox.p2.rcp.feature/feature.xml
- features/org.eclipse.equinox.p2.sdk/feature.xml
- features/org.eclipse.equinox.p2.user.ui/feature.xml
- features/org.eclipse.equinox.server.p2/feature.xml
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/917
> Version bumps for 4.28 stream

- bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/CacheManager.java
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/Messages.java
- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/messages.properties
- bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryTransport.java
https://github.com/eclipse-equinox/p2/issues/230
> Provide improved support for dealing with http protocol in p2

- bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryTransport.java
Ensure that the map used to save the per-URI retry count is thread safe and ensure that the retry count resets back to zero after a period of time.
> Fix the implementation of socket timeout retry handling.

- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/expression/CoercingComparator.java
* SuppressWarnings about deprecated AccessController usage
* Use pattern matching to reduce casts
> Code cleanup in CoercingComparator

- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustCertificateDialog.java
- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/messages.properties
Also fix typo on confirmation question for installing with revoked key.
> Fix TrustCertificateDialog regression to only show root keys

- bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/spi/IInstallableUnitUIServices.java
https://github.com/eclipse-equinox/p2/pull/249
> Fix @returns tag in IInstallableUnitUIServices

- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/AuthorityChecker.java
https://github.com/eclipse-equinox/p2/issues/262
> Fix the handling of zip:file URIs by the AuthorityChecker.

- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/AuthorityChecker.java
URIs not handled by HttpClient will throw a runtime exception, but in that case we simply want to not compute certificates for that URI not throw an exception from the method.
Fixes https://github.com/eclipse-equinox/p2/issues/262
> Ensure that invalid URIs don't fail AuthorityChecker.gatherCertificates

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
https://bugs.eclipse.org/bugs/show_bug.cgi?id=581911
> Descriptors mapped by new SimpleArtifactRepository are not "added"

- pom.xml
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100
> POM and product version changes for 4.29 release

- org.eclipse.equinox.p2.releng/default.target
Fixes: Update product version number to 4.29 across build scripts
> Update product version number to 4.29 across build scripts

- bundles/org.eclipse.equinox.p2.operations/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.updatesite/META-INF/MANIFEST.MF
- features/org.eclipse.equinox.p2.core.feature/feature.xml
- features/org.eclipse.equinox.p2.extras.feature/feature.xml
- features/org.eclipse.equinox.p2.rcp.feature/feature.xml
- features/org.eclipse.equinox.p2.sdk/feature.xml
- features/org.eclipse.equinox.p2.user.ui/feature.xml
- features/org.eclipse.equinox.server.p2/feature.xml
Needed by https://github.com/eclipse-equinox/p2/pull/276
> Version bumps for 4.29 stream

- bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/internal/p2/operations/RequestFlexer.java
- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/RemediationGroup.java
- bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/SiteBundle.java
- bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/SiteFeature.java
> Add missing "static" modifier for constants

- bundles/org.eclipse.equinox.p2.reconciler.dropins/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.reconciler.dropins/src/org/eclipse/equinox/internal/p2/reconciler/dropins/ProfileSynchronizer.java
see https://rules.sonarsource.com/java/RSPEC-2131
> Avoid wrapping primitives for toString()

- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SimpleProfileRegistry.java
- bundles/org.eclipse.equinox.p2.jarprocessor/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.jarprocessor/src/org/eclipse/equinox/internal/p2/jarprocessor/Utils.java
- bundles/org.eclipse.equinox.p2.jarprocessor/src/org/eclipse/equinox/internal/p2/jarprocessor/ZipProcessor.java
- bundles/org.eclipse.equinox.p2.jarprocessor/src/org/eclipse/equinox/internal/p2/jarprocessor/unsigner/Unsigner.java
- bundles/org.eclipse.equinox.p2.jarprocessor/src/org/eclipse/internal/provisional/equinox/p2/jarprocessor/JarProcessor.java
- bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/update/ConfigurationWriter.java
Doesn't try to fix anything. Just code and warnings reduced.
> Use try-with-resource and java.io.InputStream convenience methods

- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/PGPPublicKeyViewDialog.java
see https://github.com/eclipse-equinox/p2/pull/280#issuecomment-1595750963
> PGPPublicKeyViewDialog: avoid Date constructor

- pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1289
> POM and product version changes for 4.30 release

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepositoryIO.java
- bundles/org.eclipse.equinox.p2.tests/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.tests/pom.xml
> Warning fixes

- products/org.eclipse.equinox.p2.examples.rcp.discovery.product/cloud.product
- products/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility.product/sdkbundlevisibility.product
- products/org.eclipse.equinox.p2.ui.admin.rcp.product/rcp.product
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349
> Remove references to transitive batik dependencies from products

- products/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility.product/sdkbundlevisibility.product
https://github.com/eclipse-equinox/p2/issues/205
> Replace ECF's filetransfer.httpclient5 with filetransfer.httpclientjava

- examples/org.eclipse.equinox.p2.examples.rcp.discovery/META-INF/MANIFEST.MF
- examples/org.eclipse.equinox.p2.examples.rcp.prestartupdate/META-INF/MANIFEST.MF
- examples/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility/META-INF/MANIFEST.MF
- examples/org.eclipse.equinox.p2.examples.rcp.sdknoautoupdates/META-INF/MANIFEST.MF
- examples/org.eclipse.equinox.p2.examples.rcp.sdkui/META-INF/MANIFEST.MF
- products/org.eclipse.equinox.p2.examples.rcp.discovery.product/cloud.product
- products/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility.product/sdkbundlevisibility.product
https://github.com/eclipse-equinox/p2/issues/205
> Remove org.apache.httpcomponents.*

- bundles/org.eclipse.equinox.p2.tests.reconciler.product/pom.xml
- bundles/org.eclipse.equinox.p2.tests.reconciler.product/reconciler.product
> Version Bump for batik Change

- bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/DirectorApplication.java
https://github.com/eclipse-equinox/p2/issues/365
> Support easily generating the document for the command line options

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
https://github.com/eclipse-equinox/p2/issues/374
> Don't attempt to PGP verify folder-based content

- features/org.eclipse.equinox.p2.core.feature/feature.xml
- features/org.eclipse.equinox.p2.discovery.feature/feature.xml
- features/org.eclipse.equinox.p2.extras.feature/feature.xml
- features/org.eclipse.equinox.p2.rcp.feature/feature.xml
- features/org.eclipse.equinox.p2.sdk/feature.xml
- features/org.eclipse.equinox.p2.user.ui/feature.xml
- features/org.eclipse.equinox.server.p2/feature.xml
Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730
> Remove unnecessary attributes from feature.xml files

- bundles/org.eclipse.equinox.frameworkadmin.equinox/src/org/eclipse/equinox/internal/frameworkadmin/equinox/utils/FileUtils.java
- bundles/org.eclipse.equinox.frameworkadmin.test/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.frameworkadmin.test/src/org/eclipse/equinox/frameworkadmin/tests/TestVMArg.java
Commment lines have '#' as its first character
https://github.com/eclipse-equinox/p2/issues/361
> eclipse.ini: skip comment lines  #361

- bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/DirectorApplication.java
Currently the `DirectorApplication` internally creates or fetch an agent using the OSGi registry. If the application is used standalone (e.g. Tycho) it is sometimes desirable to have more control over this process, for this purpose there are now two new method to either fetch the default agent or acquire a new one for a given location.
@merks I restructured the flow also a bit as the previous one was quite confusing, it should now be much clearer.
Maybe you want to take a closer look if I have overseen something.
> Allow subclasses to control agent creation for DirectorApplication

- Jenkinsfile
Enable javadoc profile to get javadoc warnings too.
> Record issues in Jenkins

- bundles/org.eclipse.equinox.p2.directorywatcher/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.directorywatcher/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.operations/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui.admin/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui.sdk/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.ui.sdk/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.updatechecker/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.updatechecker/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1661 
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659
> Touch bundles affected by the changed compilation settings

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/MirrorSelector.java
Currently Tycho tests are quite unstable because it could happen that mirrors list can't be processed and then an error occur in the logs what make the test fail their "no errors".
But also as a user one might be annoyed to see errors because mirror list can't be processed.
This adds a new static MIRROR_PARSE_ERROR_LEVEL filed to allow configuration of the error level.
> Make mirror parse errors configurable

- bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/mirroring/Mirroring.java
Currently the Mirroring is performing each step independently this can lead to considerable slow down as for example the
SimpleArtifactRepository performs a save on every adding of a descriptor.
This wraps the mirror step and update of properties into a batch operation to increase performance.
> Perform the mirror step in a batch

- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductAction.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ProductActionTest.java
- bundles/org.eclipse.equinox.p2.tests/testData/ProductActionTest/brandedProduct/branded.product
https://github.com/eclipse-equinox/p2/issues/423
> Record root feature as filtered requirements in ProductAction

- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/RequiredCapability.java
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/RequiredPropertiesMatch.java
- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/Requirement.java
Current there is no information printed about min, max, greedy, or filter, which are often key to understanding the overall effect of a requirement.
This is somewhat related to https://github.com/eclipse-equinox/p2/issues/180
> Improve toString of IRequirement subclasses

- bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/IProvidedCapability.java
I think we can assumes these methods are "full API"
> Remove @noreference from IProvidedCapability

- bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/provisional/p2/artifact/repository/processing/ProcessingStep.java
- bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/ConnectorDiscoveryExtensionReader.java
- bundles/org.eclipse.equinox.p2.discovery/src/org/eclipse/equinox/internal/p2/discovery/model/Icon.java
- bundles/org.eclipse.equinox.p2.discovery/src/org/eclipse/equinox/internal/p2/discovery/model/Overview.java
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/ProfilePreferences.java
- bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/p2/metadata/io/IUSerializer.java
- bundles/org.eclipse.equinox.p2.touchpoint.natives/src/org/eclipse/equinox/internal/p2/touchpoint/natives/SimpleBackupStore.java
eliminates problem markers and dead code
> remove Exceptions not actually thrown

- bundles/org.eclipse.equinox.p2.tests/pom.xml
to get same warnings on jenkins as in workspace
> pom.xml: remove code.ignoredWarnings

- bundles/org.eclipse.equinox.p2.director/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.engine/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.metadata/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.repository.tools/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.repository/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui.sdk/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1781
> Touch bundles affected by compiler implementation change

- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/directorywatcher/DirectoryWatcherTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/EngineTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/InstructionParserTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/PhaseSetTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/PhaseTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/ProfileRegistryTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/ProfileTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/metadata/repository/MetadataRepositoryManagerTest.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/planner/AgentPlanTestInExternalInstance.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/planner/AgentPlanTestInExternalInstanceForCohostedMode.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/simpleconfigurator/SimpleConfiguratorUtilsTest.java
Improves readability of the tests.
> Use assertThrows in p2 tests

- bundles/org.eclipse.equinox.frameworkadmin.test/build.properties
- bundles/org.eclipse.equinox.p2.tests.discovery/build.properties
- bundles/org.eclipse.equinox.p2.tests.ui/build.properties
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1628
> remove ignoredWarnings

- bundles/org.eclipse.equinox.p2.director.app/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.operations/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.reconciler.dropins/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/forceQualifierUpdate.txt
See https://github.com/eclipse-equinox/p2/pull/439
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1801
> Touch bundles affected by PhaseSetFactory static field changes

- Jenkinsfile
error was:
"Repository miner is not configured, skipping repository mining Reference build recorder is not configured
Obtaining reference build from same job"
> Jenkinsfile: enable eclipse qualityGate

- bundles/org.eclipse.equinox.p2.artifact.repository/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.metadata/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.repository.tools/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.tests/forceQualifierUpdate.txt
- bundles/org.eclipse.equinox.p2.ui/forceQualifierUpdate.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1979
> Touching bundles after compiler change

- docs/p2_index.md
For https://github.com/eclipse-equinox/p2/issues/497
> Migrate p2_index wiki pages to mark-down

- features/org.eclipse.equinox.server.p2/feature.xml
Due to change in org.eclipse.equinox.app: https://github.com/eclipse-equinox/equinox/pull/647
> Version bump for 4.33 stream

- bundles/org.eclipse.equinox.p2.discovery.compatibility/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/util/CacheManager.java
https://github.com/eclipse-equinox/p2/issues/536
> CacheManager.updateCache moves a resource but has an open stream on

- features/org.eclipse.equinox.p2.core.feature/feature.xml
- features/org.eclipse.equinox.p2.extras.feature/feature.xml
- features/org.eclipse.equinox.p2.rcp.feature/feature.xml
- features/org.eclipse.equinox.p2.sdk/feature.xml
- features/org.eclipse.equinox.p2.user.ui/feature.xml
- features/org.eclipse.equinox.server.p2/feature.xml
- There is a new version of org.eclipse.equinox.preferences.
https://github.com/eclipse-equinox/equinox/pull/663
> Update org.eclipse.equinox.p2.core.feature to 1.7.400

- bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2358
> Touch because of compiler changes.

- bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/DownloadManager.java
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Messages.java
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/messages.properties
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/Collect.java
- bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/ProvisioningContext.java
Backporting : Ensure that a jar:file: URI is considered local for artifact and Improve message if artifact can not be downloaded from any repository to R4_31_ maintenance branch.
> BackPort: Ensure that a jar:file: URI is considered local for artifact

- README.md
- releng/org.eclipse.equinox.p2.setup/.project
- releng/org.eclipse.equinox.p2.setup/.settings/org.eclipse.core.resources.prefs
- releng/org.eclipse.equinox.p2.setup/EquinoxP2Configuration.setup
Additionally add a styled and drag&drop-able Oomph Configuration button to the main README.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2430
> [Oomph-Setup] Add equinox.p2 configuration setup

- bundles/org.eclipse.equinox.p2.tests/META-INF/MANIFEST.MF
- bundles/org.eclipse.equinox.p2.tests/pom.xml
As reported at
https://download.eclipse.org/eclipse/downloads/drops4/I20241218-0320/buildlogs/reporeports/reports/versionChecks.html
> Version bump for new stream

- bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java
Currently there is a class instance shared field used for final waiting but actually it could be handled locally in the method, this also removes the need for keeping the browseRequest around.
> Replace global waiting flag by local latch, remove browseRequest field

- bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java
Currently error handling is performed with a shared class field on two different places.
This now inline the event handling in a way it does not need a global field and handles the exception locally.
> Inline eventhandling and remove need for exception field

- .github/workflows/checkDependencies.yml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/.github/workflows#checkdependenciesyml
> Add workflow that checks for bundle dependencies version ranges

- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/FeatureParser.java
- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java
- bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/pde/internal/swt/tools/IconExe.java
- bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/JREAction.java
- bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/spi/p2/publisher/LocalizationHelper.java
and fix warning regarding the use of the deprecated method File.toURL()
> Use try-with-resources in p2.publisher bundles

- bundles/org.eclipse.equinox.p2.ui.discovery/src/org/eclipse/equinox/internal/p2/ui/discovery/util/PatternFilter.java
Fixes warning as listed in
https://download.eclipse.org/eclipse/downloads/drops4/I20250317-1800/compilelogs/plugins/org.eclipse.equinox.p2.ui.discovery_1.3.600.v20250317-0608/@dot.html
> Remove unused SuppressWarnings

- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustAuthorityDialog.java
- bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustCertificateDialog.java
> Use SWT APPLICATION_MODAL instead of ON_TOP for TrustCertificateDialog

- bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/AbstractApplication.java
- bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/CompositeRepositoryApplication.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/AbstractRepositoryTask.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/CompositeRepositoryTask.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/MirrorTask.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/RemoveIUTask.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/Repo2RunnableTask.java
- bundles/org.eclipse.equinox.p2.repository.tools/src_ant/org/eclipse/equinox/p2/internal/repository/tools/tasks/ValidateTask.java
- bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/mirror/MetadataMirrorApplicationTest.java
@merks, @laeubi or @akurtakov, can you tell if the protected fields of the ANT tasks are considered internal?
> Clean-up and unify repo-applications and P2 repo-tools ANT tasks
