bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/MirrorRequest.java

Add a new system property `eclipse.p2.reportDownloadStatistics` which allows to opt out of reporting download statistics to `p2.statsURI/download.stats` defined in the artifact repository.
This is especially useful in situations where the P2 director `org.eclipse.equinox.p2.director` is used to build distributions from local repository mirrors.
The download statistics reporting could take a significant amount of time and there was no way to opt out other than modifying the local repository mirror and removing the `p2.statsURI` / `download.stats` properties from `artifacts.xml`.

Bug 368073 - Allow users to opt out of uploading download statistics

---

bundles/org.eclipse.equinox.p2.tests/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/JREActionTest.java

Not only it's one dependency less but even the assertion is easier to
understand.

Stop using hamcrest-library in p2 tests.

---

features/org.eclipse.equinox.p2.core.feature/feature.xml
features/org.eclipse.equinox.p2.sdk/feature.xml

sat4j is already included transtively by Require-Bundle for
org.eclipse.equinox.p2.director. So we don't need to add it
explicitly, and that will facilitate further verison upgrades
as the version wouldn't be statically replaced.

Remove inclusion of sat4j in feature.xml (#28)

---

bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileReader.java

Terminate the job's loop when the enclosing FileReader no longer has a reference to the CancelHandler job.

Some FileReader.CancelHandler jobs never terminate #36

---

bundles/org.eclipse.equinox.p2.director/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.director/src/org/eclipse/equinox/internal/p2/director/Projector.java
bundles/org.eclipse.equinox.p2.director/src/org/eclipse/equinox/internal/p2/director/SimplePlanner.java

Add a close method to Projector which resets the dependency helper,
which ensures that any threads are canceled.
Call the close method after the usage of the Projector has completed.
https://github.com/eclipse-equinox/p2/issues/45

The use of sat4j by p2 leaks solver instances via threads spawned by sat4j

---

bundles/org.eclipse.equinox.p2.tests.reconciler.product/reconciler.product

Second attempt to fix the p2.tests.reconciler product without improving it to use features.
With the latest changes in Equinox (https://github.com/eclipse-equinox/equinox.framework/issues/40) o.e.osgi.util was replaced by the corresponding 'original' OSGi-reference bundles that are required+re-exported by o.e.osgi.util. Unfortunately the re-export does not help in plug-in based products, but 'o.e.osgi.util' seems not to be necessary so it is just removed.

Fix p2.tests.reconciler product

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

With https://github.com/eclipse-equinox/equinox.bundles/pull/39 the sources of `org.osgi.service.prefs` in `org.eclipse.equinox.preferences` are replaced by the original osgi-bundle.
This change adds that bundle to features that include `org.eclipse.equinox.preferences` to ensure the sources stay available.
This is part of:
https://github.com/eclipse-equinox/equinox.framework/issues/40

Add OSGi service.prefs bundle to features

---

bundles/org.eclipse.equinox.p2.touchpoint.eclipse/META-INF/MANIFEST.MF

Fix a predicted compilation error in the current I-Build: https://ci.eclipse.org/releng/job/I-build-4.24/96 
(at least I have corresponding errors in my workspace).
That failure is due to the replacement of embedded OSGi sources by their 'original' OSGi bundles performed in 
https://github.com/eclipse-equinox/equinox.bundles/pull/39
@tjwatson, @laeubi that's the same scenario like in https://github.com/eclipse-equinox/equinox.bundles/pull/31
But this time it is the other way round: `org.osgi.service.prefs` was imported which seems to have made `org.eclipse.core.runtime.preferences` available for compilation.

Add missing Package-Import of org.eclipse.core.runtime.preferences

---

bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/core/BackupTest.java
bundles/org.eclipse.equinox.p2.touchpoint.natives/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.touchpoint.natives/src/org/eclipse/equinox/internal/p2/touchpoint/natives/SimpleBackupStore.java

This is a fix for Bug 579807
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579807.
The change in SimpleBackupStore to use the Java NIO API does not close the stream opened by a call to Files.list. This can cause subsequent operations on the directory to fail. Specifically in CleanupZipAction the directory can still exists after deletion but in a inaccessible state.
On machines where this issue occurs the existing test case CleanupzipActionTest#testDirectoryCleanup will fail. In my experience these are Windows Server 2016 instances on AWS.

Use try-with-resources to close Stream opened by Files.list in SimpleBackupStore

---

features/org.eclipse.equinox.p2.sdk/feature.xml
features/org.eclipse.equinox.server.p2/.project
features/org.eclipse.equinox.server.p2/.settings/org.eclipse.core.runtime.prefs
features/org.eclipse.equinox.server.p2/build.properties
features/org.eclipse.equinox.server.p2/feature.properties
features/org.eclipse.equinox.server.p2/feature.xml
features/org.eclipse.equinox.server.p2/forceQualifierUpdate.txt
pom.xml

In https://github.com/eclipse-equinox/equinox.bundles/pull/40#issuecomment-1116670974 it was discussed to move the o.e.equinox.server.p2 feature into the p2 repository since it mainly consists of p2 plug-ins and therefore should reside in the same repository.
This the addition part of the move. The removal is performed in https://github.com/eclipse-equinox/equinox.bundles/pull/42.

Move equinox.server.p2 into p2 repository

---

features/org.eclipse.equinox.server.p2/feature.xml

Including `o.e.equinox.p2.core.feature` in the `o.e.equinox.server.p2` feature simplifies the latter a lot.
This change would effectively add the following plug-ins to o.e.equinox.server.p2:
- org.eclipse.equinox.p2.operations
- org.eclipse.equinox.security.macosx
- org.eclipse.equinox.security.linux
- org.eclipse.equinox.security.win32.x86_64
- org.tukaani.xz
- org.bouncycastle.bcpg
- org.bouncycastle.bcprov
- org.eclipse.equinox.concurrent
But since those plug-ins are listed at the very end of p2.core I wonder if server.p2 was initially intended to contain everything in p2.core and was not updated to contain those plug-ins that are effectively added with this change.
This is a follow-up of https://github.com/eclipse-equinox/p2/pull/62 and can be submitted subsequently.
This change was …

Simplify server p2 feature

---

bundles/org.eclipse.equinox.frameworkadmin.test/pom.xml
bundles/org.eclipse.equinox.p2.director.app/pom.xml
bundles/org.eclipse.equinox.p2.installer/pom.xml
bundles/org.eclipse.equinox.p2.reconciler.dropins/pom.xml
bundles/org.eclipse.equinox.p2.tests.discovery/pom.xml
bundles/org.eclipse.equinox.p2.tests.reconciler.product/pom.xml
bundles/org.eclipse.equinox.p2.tests.ui/pom.xml
bundles/org.eclipse.equinox.p2.tests.verifier/pom.xml
bundles/org.eclipse.equinox.p2.tests/pom.xml
bundles/org.eclipse.equinox.p2.ui.admin.rcp/pom.xml
examples/org.eclipse.equinox.p2.examples.rcp.discovery/pom.xml
examples/org.eclipse.equinox.p2.examples.rcp.prestartupdate/pom.xml
examples/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility/pom.xml
examples/org.eclipse.equinox.p2.examples.rcp.sdknoautoupdates/pom.xml
examples/org.eclipse.equinox.p2.examples.rcp.sdkui/pom.xml
examples/pom.xml
org.eclipse.equinox.p2.releng/default.target
org.eclipse.equinox.p2.releng/org.eclipse.equinox.p2.tests-parent/pom.xml
pom.xml

Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
Need to wait to merge until after 4.24 Release

WIP: POM and product version changes for 4.25 release

---

bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/ApplyProfileChangesDialog.java
features/org.eclipse.equinox.p2.rcp.feature/feature.xml
features/org.eclipse.equinox.p2.sdk/feature.xml
features/org.eclipse.equinox.p2.user.ui/feature.xml

Operating system Ui guidelines do not recommend the usage of the help
icon in a dialog. For example check the screenshots in the Windows
guidelines for dialogs.
Operating System UI Guidelines
Windows UI guidence
https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs
Gnome UI guidence
https://developer.gnome.org/hig/patterns/feedback/dialogs.html
Mac UI guidence
https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/

Remove the help icon from the restart after installation dialog

---

bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/p2/ui/RevertProfilePage.java

To trigger this dialog use Help -> About -> Installation Details ->
Installation History and select an older state and press the Revert
button.
Operating system Ui guidelines do not recommend the usage of the help
icon in a dialog. For example check the screenshots in the Windows
guidelines for dialogs.
Operating System UI Guidelines
Windows UI guidence
https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs
Gnome UI guidence
https://developer.gnome.org/hig/patterns/feedback/dialogs.html
Mac UI guidence
https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/

Remove the help icon from the revert profile page

---

features/org.eclipse.equinox.p2.core.feature/forceQualifierUpdate.txt

As some included bundles have changed with the move away from Orbit to
Maven.

Force qualifier update for p2.core.feature

---

bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/CopyUtils.java

Currently activateCopy fails if no workbench is running, but all
services are optional, so it seems valid to assume that no workbench
could be handled like no services aviable.

Guard CopyUtil optional services access with workbench running

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

This reverts commit 2253646b033770abf40d67823759efe1370d1863.
BouncyCastle from Central has jarsignature in with unrooted certificate,
currently causing Trust dialog to popup.
Will restore to use Maven Central when this issue is fixed.

Revert "Use bouncycastle from Maven Central"

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/FileUtils.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/core/FileUtilsTest.java

Solution copied from Bug 573456 / o.e.osgi.storage.Storage#getFile:
File.getCanonicalPath is much slower then java.nio.file.Path.normalize
under windows. Also avoid normalization if no ".." is involved.
tested by
org.eclipse.equinox.p2.tests.core.FileUtilsTest.testUnzipEscapeZipRoot()

Avoid File.getCanonicalPath

---

bundles/org.eclipse.equinox.p2.director.app/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.director.app/plugin.xml
bundles/org.eclipse.equinox.p2.director.app/pom.xml

The application used of the mentioned product has been removed with [Bug 308653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=308653) respectively [Bug 291475](https://bugs.eclipse.org/bugs/show_bug.cgi?id=291475). Due to some back and forth removing that application it looks like the mentioned product has been forgotten to be removed eventually.

Remove unusable o.e.equinox.p2.director.app.product

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/ServiceHelper.java

currently only half of the methods do a null check for the bundle
context the other simply run ino a NPE. This adds the missing checks,
see also https://github.com/eclipse-equinox/p2/issues/100

Add consistent null checks to ServiceHelper

---

.github/matcher.json

Thanks to
- https://github.com/eclipse-pde/eclipse.pde/pull/264
we can now greatly simplify the matcher and get full annotation support for API problems withing GH action builds:

Update the matcher pattern according to new ApiTools output

---

bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/CacheManager.java

Added system property -Dp2.skipRepositoryProtocolCheck=true that allows users to run
Eclipse without getting dozens of "Using unsafe http transport" p2
warnings on every p2 update task.
Fixes https://github.com/eclipse-equinox/p2/issues/123

Allow users mute "Using unsafe http transport" p2 warnings (#123)

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/spi/package.html

As found by Java 17 javadoc tool.
Needed by
eclipse-platform/eclipse.platform.releng.aggregator#482

Another round of Javadoc warnings and errors.

---

bundles/org.eclipse.equinox.p2.tests.reconciler.product/reconciler.product
bundles/org.eclipse.equinox.p2.ui.admin.rcp/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.admin.rcp/pom.xml
bundles/org.eclipse.equinox.p2.ui.admin.rcp/rcp.product
examples/org.eclipse.equinox.p2.examples.rcp.discovery/cloud.product
examples/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility/sdkbundlevisibility.product

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/489

replacing org.apache.commons.io with org.apache.commons.commons-io

---

Jenkinsfile

Otherwise no module can enable skipTests.
@mickaelistria is there any reason (that is still relevant), that this property was set?
And remove 'maven.test.error.ignore=true' and 'maven.test.failure.ignore=true' because the build already has '--fail-at-end' set

Don't set system-property skipTests=false in Jenkins build

---

Jenkinsfile

This reverts parts of https://github.com/eclipse-equinox/p2/pull/143.

Revert removal of maven.test.error/failure.ignore in Jenkins build

---

.gitignore
bundles/org.eclipse.equinox.frameworkadmin.test/pom.xml
bundles/org.eclipse.equinox.p2.tests.discovery/pom.xml
bundles/org.eclipse.equinox.p2.tests.reconciler.product/pom.xml
bundles/org.eclipse.equinox.p2.tests.ui/pom.xml
bundles/org.eclipse.equinox.p2.tests.verifier/pom.xml
bundles/org.eclipse.equinox.p2.tests/pom.xml
examples/pom.xml
org.eclipse.equinox.p2.releng/org.eclipse.equinox.p2.tests-parent/pom.xml
pom.xml

This will make it easier to publish correct maven-metadata and deploy to
eclipse-maven-repository.
See https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#enhanced-support-for-maven-ci-friendly-versions
Also enables controlling the inclusion of pom

Use Tycho-CI-Friendly-Versions

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java
bundles/org.eclipse.equinox.p2.tests/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.tests/pom.xml
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/BundlesActionTest.java
bundles/org.eclipse.equinox.p2.tests/testData/multiVersionCapability/bundle1/META-INF/MANIFEST.MF

This PR aims to fix the flawed read/processing of provided Generic-capbailities that have a list of versions, which was discovered in https://github.com/eclipse-equinox/equinox.framework/pull/44#issuecomment-1116711351.
I think I should add some tests for this.
Furthermore I would like to test this fix first locally with Tycho as described here:
https://github.com/eclipse/tycho/blob/master/CONTRIBUTING.md#building-tycho-against-a-locally-built-version-of-p2

Fix creation of generic-capabilities with multiple versions

---

bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/processors/checksum/ChecksumUtilities.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/ChecksumProducer.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/AllTests.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/ProduceChecksumTest.java

Currently the file is read for each checksum algorithm. While calculating checksums is fast, disk I/O is often not.
This changes the method that calculates the hashes in a way that the data is only read once but chained to each algorithm.
As discussed here: https://github.com/eclipse-equinox/p2/pull/160
I think this can actually be speedup even more by caching the digest itself, but that's a different story...

Do not read data multiple times when calculating checksum

---

bundles/org.eclipse.equinox.p2.artifact.repository/plugin.xml
bundles/org.eclipse.equinox.p2.artifact.repository/schema/artifactChecksums.exsd
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/processors/checksum/ChecksumUtilities.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/processors/checksum/ChecksumVerifier.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/ChecksumPriorityTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/ChecksumVerifierTest.java

Currently always all checksums are checked for integrity of a file, this change the behavior by introducing a ranking and only checks the best matching one.
This is another spin-off from #160

Always choose the most secure algorithm to check integrity

---

bundles/org.eclipse.equinox.p2.artifact.repository/schema/artifactChecksums.exsd
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/processors/checksum/ChecksumUtilities.java

Currently all registered checksums are computed and published, but in some cases it might be usefully to be able to verify a checksum but we don't want to publish it
It seems it was to ambitious to disable md5 as part of the change, so here is just the extract from
- https://github.com/eclipse-equinox/p2/pull/164
that only *allows* to disable checksums but actually do not change anything at P2 in that regard (what would better be handled in a separate change).

Add an option to disable checksum publishing

---

bundles/org.eclipse.equinox.p2.artifact.repository/plugin.xml
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/processors/AllTests.java

SHA1 is the default signature for maven and recently support was added up to sha-512 so P2 should support this as well.

Support sha1/512 as additional checksums in P2

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/MirrorSelector.java

Fix https://github.com/eclipse-equinox/p2/issues/176

MirrorSelector.reportResult does not handle UNKNOWN_RATE

---

bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/KeySigningInfoFactory.java

Occasionally I see error reports about an NPE in `KeySigningInfoFactory` because the `bundlePoolRepository` is null.
Unfortunately I don't have any at hand now because I did the change a while ago but somehow did not submit it.
@merks can you tell if this change is reasonable?
And also apply some slight modernization/simplifications of the code.

Fix NPE in KeySigningInfoFactory and slightly modernize it

---

bundles/org.eclipse.equinox.frameworkadmin.equinox/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.frameworkadmin.equinox/src/org/eclipse/equinox/internal/frameworkadmin/equinox/EquinoxFwConfigFileParser.java

avoids warning "Failed creating shared configuration url for null."

EquinoxFwConfigFileParser: add null check - fixes #219

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/Messages.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/messages.properties
bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryTransport.java

Deal with both ftp and http protocol. The system property p2.{protocol}Rule can be used to configure the behavior.
https://github.com/eclipse-equinox/p2/issues/230

Generalize support for dealing with insecure protocols in p2

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/expression/CoercingComparator.java

Rawtypes one was removed by error while moving to Java 17 and AccessController.doPrivileged has no clear replacement and stays until JVM actually removes this one.
https://github.com/eclipse-platform/eclipse.platform/issues/385 is the general tracking issue for SecurityManager removal in the JVM

Silence warnings in CoercingComparator

---

bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java

Use the system property org.eclipse.equinox.p2.type.lock as a mask for setting that IU property lock state, e.g., setting it to 0 will leave the mask as specified in the user profile, 1 will lock it only for uninstall, and 3 is what it does by default, which is to look for uninstall and update.
Fixes https://github.com/eclipse-equinox/p2/issues/254

Support a system property for surrogate profile IU lock state

---

bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/.settings/org.eclipse.core.resources.prefs
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/AutomaticUpdateMessages.java
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/AutomaticUpdater.java
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/AutomaticUpdatesFailPopup.java
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/AutomaticUpdatesPopup.java
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/UpdatesPopup.java
bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/messages.properties
org.eclipse.equinox.p2.releng/default.target

Fixes #254.
Function is enabled with JVM argument `-Dorg.eclipse.equinox.p2.ui.sdk.scheduler.warnLocked=true`
Automatic update check fails silently on write-protected installations.
Explicit check for updates shows message "Insufficient access privileges to apply this update".
If automatic update check fails due to insufficient privileges, user is presented with a new popup:
On click, an update dialog shown, just like for explicit "Check For Updates", allowing user to see which updates can't be installed.

Notify user about updates for write-protected components

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/CacheManager.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/Messages.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/messages.properties
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/repository/CacheManagerTest.java

Method
createCacheFromFile()
was introduced in
Bug 464614 - Use XZ as compression formats of metadata files
and is more a less a simplified copy of
createCache()
which only deals with a single URI, instead of two (with and without .jar appended).
However, the condensed exception handling was missing important branches and swallowed too many exceptions. This caused that a FileNotFoundException Was silently swallowed and the low-level Transport was asked anyways, instead of bailing out with a proper PrivisionException immediately.
The low-level Transport then, after sending another redundant HTTP request, returned a ProvisionException with improper status code (ARTIFACT_NOT_FOUND instead of REPOSITORY_NOT_FOUND).
Fixes #257.

CacheManager: Fix exception handling

---

bundles/org.eclipse.equinox.p2.ui.discovery/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.discovery/src/org/eclipse/equinox/internal/p2/ui/discovery/util/TextSearchControl.java
features/org.eclipse.equinox.p2.discovery.feature/feature.xml

Avoiding type-casts makes code easier to read.

Use typed for-each loop

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/FileUtils.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ExecutablesDescriptor.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/pde/internal/build/publisher/GatheringComputer.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/AbstractProvisioningTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/core/FileUtilsTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/full/AbstractEnd2EndTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/metadata/repository/JarURLMetadataRepositoryTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/planner/Bug362692.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/AccumulateConfigDataActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/BundlesActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/FeaturesActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/RootFilesActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/reconciler/dropins/AbstractSharedBundleProductTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/repository/CacheManagerTest.java
bundles/org.eclipse.equinox.p2.touchpoint.eclipse/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/touchpoint/eclipse/PublisherUtil.java

Use the new IPath factory methods introduced in https://github.com/eclipse-equinox/equinox/pull/228 in P2.
With this PR the `org.eclipse.core.runtime.Path` does not occur anymore in P2's entire code base.

Use new static IPath factories and constants

---

bundles/org.eclipse.equinox.p2.tests/pom.xml
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/reconciler/dropins/AbstractReconcilerTest.java

Currently the P2 test rely on the existence of the reconciler product, but as there is no requirement maven might have not build the product yet.
This adds a (pom) dependency to the reconciler project so maven always builds the project first.

Fix failing test in case the build-order is different

---

bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/Activator.java
bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/persistence/CompositeParser.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/persistence/CompositeRepositoryIO.java

The CompositeParser `BundleContext` parameter is actually unused, removing this also allows to cleanup further things that previously required static access to the Activator class.
FYI @merks do you see any issues with that?

Remove unused composite parser parameter

---

.mvn/maven.config

Lets see if this fixes the issue with windows build not publishing tests...

Add option to delete the workdir to fix GH action test result collection

---

bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/PGPPublicKeyViewDialog.java

SimpleDateFormat is not thread-safe.
SimpleDateFormat.format(new Date());
returns same string as immutable and thread-safe
DateTimeFormatter.format(new Date().toInstant())

Avoid reuse of SimpleDateFormat

---

bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/Activator.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/LogHelper.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/Tracing.java

Currently two classes only access the "instance" of the Activator class in a static way what often is a source of failures when using P2 in other context as a potential NPE can occur.
This replaces the static access with some OSGi low level access that will fullfill a similar purpose but do not require to tie these to the activator class.

Remove static Activator reference access

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

This allows updating deps without touching features.

Do not include Bouncycastle bundles in p2.core feature

---

bundles/org.eclipse.equinox.p2.ui.discovery/src/org/eclipse/equinox/internal/p2/ui/discovery/wizards/DiscoveryResources.java

Replace `ResourceManager` methods deprecated since https://github.com/eclipse-platform/eclipse.platform.ui/pull/838.

Replace deprecated ResourceManager methods

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/Messages.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/RepositoryHelper.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/messages.properties

Currently if one tries to use a custom ecf scheme the first time the install dialog complains that the scheme is not supported. A user has first use some standard scheme (e.g. http) then ECF is loaded and the custom scheme can be used.
This enhance the repository check in a way that it discovers ECF available schemes at the first place.

Discover ECF provided schemes

---

bundles/org.eclipse.equinox.p2.reconciler.dropins/plugin.xml
bundles/org.eclipse.equinox.p2.tests.reconciler.product/reconciler.product

The p2.tests.reconciler product can be simplified significantly if it is converted to be feature based.
But this requires a mixed product since no feature (except for the SDK) contains the `org.eclipse.equinox.p2.installer` plug-in, which seems to be necessary.
At the moment this seems not to work (altough Tycho should support this). I will investigate it further when completing [Bug 325614](https://bugs.eclipse.org/bugs/show_bug.cgi?id=325614).

Simplify p2.tests.reconciler product

---

org.eclipse.equinox.p2.releng/default.target

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1235
Additionally update to new Orbit Repo and set targetJRE to match the requirement of P2 for Java-17.
I didn't test it full to build p2 against it, but it at least resolves in my workspace.

Replace obsolete product unit by its contained feature-units

---

bundles/org.eclipse.equinox.p2.metadata/.settings/.api_filters
bundles/org.eclipse.equinox.p2.metadata/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/expression/QueryResult.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/CollectionResult.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/Collector.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/IQueryResult.java

This improves the interoperability of `IQueryResult` and the Java's modern Stream-API.
Additionally Clean-up `IQueryResult` and its implementations in a separate first commit.

Add new method IQueryResult.stream()

---

bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/ProvisioningContext.java

- Use SubMonitor.split() over newChild()
- Remove explicit checks for cancellation since SubMonitor.split() does that implicitly
- Simplify work computation by avoiding unnecessary multiplies When creating a split SubMonitor the splitted child only operates on the assigned amount of work.

Enhance ProgressMonitor usage in ProvisioningContext

---

bundles/org.eclipse.equinox.p2.director/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.director/src/org/eclipse/equinox/internal/p2/director/QueryableArray.java
bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Profile.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/ProfileMetadataRepository.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/ProvisioningPlan.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/ProvisioningContext.java
bundles/org.eclipse.equinox.p2.extensionlocation/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.extensionlocation/src/org/eclipse/equinox/internal/p2/extensionlocation/ExtensionLocationMetadataRepository.java
bundles/org.eclipse.equinox.p2.metadata.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/CompositeMetadataRepository.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/LocalMetadataRepository.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/URLMetadataRepository.java
bundles/org.eclipse.equinox.p2.metadata/.settings/.api_filters
bundles/org.eclipse.equinox.p2.metadata/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/CompoundQueryable.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/query/IQueryable.java
bundles/org.eclipse.equinox.p2.publisher/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/PublisherResult.java
bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/ICompositeRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/IRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/IArtifactRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/IMetadataRepository.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/TestMetadataRepository.java
bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/query/QueryableProfileRegistry.java
bundles/org.eclipse.equinox.p2.updatesite/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/metadata/UpdateSiteMetadataRepository.java

This methods provides a more convenient and in most cases faster way to test if a repository contains an element, compared to querying the repository for it.
`IArtifactRepository` already has a contains() method so this effectively only adds it for `IMetadataRepository` and generalizes it.
The implementation is based on the query() or everthing() implementation of the corresponding class, if possible.
The first of the two commits contains the clean-ups in the the `IRepository` and `IArtifactRepository` interfaces.

Add IRepository.contains(T) method

---

bundles/org.eclipse.equinox.p2.directorywatcher/forceQualifierUpdate.txt

Side effect from c43af59 / https://github.com/eclipse-equinox/p2/pull/314
Fixes https://github.com/eclipse-equinox/p2/issues/320

Comparator error with CachingArtifactRepository in build I20230915-0520

---

features/org.eclipse.equinox.p2.core.feature/build.properties
features/org.eclipse.equinox.p2.extras.feature/build.properties
features/org.eclipse.equinox.p2.rcp.feature/build.properties

These files no longer exist in the repo as they are taken by the license feature.

Remove old and wrong src.includes from features

---

bundles/org.eclipse.equinox.p2.engine/forceQualifierUpdate.txt
bundles/org.eclipse.equinox.p2.metadata/forceQualifierUpdate.txt
bundles/org.eclipse.equinox.p2.ui.sdk/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.sdk/forceQualifierUpdate.txt
bundles/org.eclipse.equinox.p2.ui/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1378

Touch bundles affected by changed bytecode generation

---

bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/CompositeMetadataRepository.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/LocalMetadataRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/IMetadataRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/spi/AbstractMetadataRepository.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/TestMetadataRepository.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/metadata/repository/LocalMetadataRepositoryTest.java
bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/metadata/UpdateSiteMetadataRepository.java

In order to allow removing references to other repositories from an `IMetadataRepository`, just like one can also remove IUs, this adds an `IMetadataRepository.removeReferences(Collection)` method and implements it in all classes that also implement `IMetadataRepository.addReferences()`.
I have not yet added them, but a little test-case, at least for the most imporant implementation `LocalMetadataRepository` would probably be good.

Add IMetadataRepository.removeReferences()

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/spi/RepositoryReference.java

Actually `RepositoryReference` would be a good candidate for a record, but this would be a binary incompatible change and thus a breaking change for this API class (even if we retain the getters).

Add RepositoryReference.toString() to simplify debugging

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/IInstallableUnitQueryable.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/IMetadataRepository.java

Currently there is only the generic IQueryable<T> but this don't work well in cases where one can't pass type information for the generic e.g. when adapting an object there is no way to pass the parameter T.
This adds a new interface that lock in the type T for a IQueryable that can supply IInstallableUnits.
This is a prerequisite of https://github.com/eclipse-pde/eclipse.pde/issues/207 where I'd like to use the Adapter pattern to support other locations to supply additional Installable units.

Add IInstallableUnitQueryable interface to allow easier adaption

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ArtifactKey.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/InstallableUnit.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ProvidedCapability.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/RequiredCapability.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/Requirement.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ResolvedInstallableUnit.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/MetadataFactory.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/spi/ArtifactDescriptor.java

This also improves the `hashCode()` function of Requirement.

Modernize internal p2 metadata Member classes

---

bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustAuthorityDialog.java
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustCertificateDialog.java

Use SWT.ON_TOP for the shell in order to keep the dialogs visible, because generally the user cannot proceed with their activity (update/install) until the dialog is completed.
A modal dialog is avoided because these dialogs are asynchronously opened from a background job, which blocks, so there is no knowing what UI activity might currently be under way.
https://github.com/eclipse-oomph/oomph/issues/11

Prevent trust dialogs from being hidden behind the application window

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ConfigCUsAction.java

P2 part of https://github.com/eclipse-equinox/p2/issues/345

Add support for Product Update-site names

---

bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/SimpleMetadataRepositoryFactory.java

Currently we rely on the file-ending to determine the type of file but this can fail in cases a CacheManger returns a cached file without that extension (for whatever reason).
This now adds another check for content sensing if the simple check fails to ensure a zipped item is not parsed as plain text.

Do content sensing to make sure the file is really not a jar

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/AbstractRepositoryManager.java

Currently unavailableRepositories is not synced what can lead in some rare cases to strange behaviors.
This now uses the existing reporistoryLock to make sure only one thread is acessing the datastructure at a time.

Syncronize on unavailableRepositories before access the list

---

bundles/org.eclipse.equinox.p2.director.app/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/DirectorApplication.java

When modifying DirectorApplication, the save actions generally transform and reformat the source code because those actions where not applied in the past. This makes it difficult to see what is being semantically modified versus which is modified by sematnic-perserving the save actions. Apply these changes now, once and for all.
https://github.com/eclipse-equinox/p2/issues/365

Improve the formatting of DirectorApplication

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/IProductDescriptor.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductFileAdvice.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ProductFileTest.java

Remove unused distinction between Plug-ins and Fragments in `.product` files.
There is no usage of a product's fragments in P2 or PDE.
I also checked Tycho (5 but I assume it's the same for Tycho 4) and it never calls `IProductDescriptor.getFragments()` and calls `IProductDescriptor.getBundles(boolean includeFragments)` with `includeFragments=true`.
So it looks like this distinction is unused and can be removed too.
Consequently PDE support for adding a fragment attribute for fragments listed in a product file can be removed too and I will create a PR dedicated to that.
This was originally part of https://github.com/eclipse-equinox/p2/pull/368, but since the second part there needs some more adoptions in PDE I will postpone that but would like to land this for the December release.

Remove unused distinction between Plug-ins and Fragments in products

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/RawMirrorRequest.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Engine.java
bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/ProfileChangeOperation.java
bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/ProfileModificationJob.java
bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/ProvisioningSession.java
bundles/org.eclipse.equinox.p2.tests.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.tests.ui/src/org/eclipse/equinox/p2/tests/ui/AbstractProvisioningUITest.java
bundles/org.eclipse.equinox.p2.tests.ui/src/org/eclipse/equinox/p2/tests/ui/dialogs/UpdateWizardTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/AbstractProvisioningTest.java
bundles/org.eclipse.equinox.p2.ui.importexport/src/org/eclipse/equinox/internal/p2/importexport/internal/wizard/ImportWizard.java
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/ProvisioningOperationWizard.java
examples/org.eclipse.equinox.p2.examples.rcp.prestartupdate/src/org/eclipse/equinox/p2/examples/rcp/prestartupdate/P2Util.java

passing a monitor to two callees requires it to be splitted.
https://github.com/eclipse-equinox/p2/issues/335
Also fixed forgotten monitor.done() in performProvisioningPlan and improved tests.

ProfileChangeOperation: fix progressmonitor usage #335

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/RepositoryHelper.java

Just log an exception and return an empty list in the unlikely event of failure.
https://github.com/eclipse-equinox/p2/issues/373

Improve RepositoryHelper.getSharedBundlePools() to avoid exceptions

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/RepositoryHelper.java

Oomph has moved the encoding.info to be in the same folder as the agents.info which lists all the agent locations (rather than in the folder of the default agent's location). The agents.info file can be loaded to determine the location of the pools.info of each agent. This refined approach covers the full generality of Oomph's shared agent manager allows all pools of all agents to be located with no assumptions about defaults.
https://github.com/eclipse-equinox/p2/issues/373

Improve RepositoryHelper.getSharedBundlePools to load all agent pools

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

FYI @akurtakov @merks @tjwatson requires PL/PMC approval
See
- https://github.com/eclipse-equinox/p2/issues/381
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/86

Require ecf http5 in core feature

---

bundles/org.eclipse.equinox.p2.tests/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.tests/pom.xml

The bundle is excluded from comparison as it contains broken zips that break it (as per comment in the pom) thus it was not autodetected. Removed the org.eclipse.osgi.compatibility.state extra dep for surefire as it shouldn't be needed anymore.

Version bump for pde.tests for 4.31

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeaturesAndBundlesPublisherApplication.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/InstallPublisherApplication.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductPublisherApplication.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/AbstractPublisherApplication.java
bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/CategoryPublisherApplication.java
bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/UpdateSitePublisherApplication.java

Currently the agent is always determined implicitly by query the service registry, even though one can extend the application and the overwrite `setupAgent` it seems much more suitable to offer a way to set the agent at construction time.
@merks this should be transparent for existing code but just in case you maybe can have a deeper look at this.
I noticed that the lack of constructor is one reason Tycho currently uses some workaround or extends applications and so other might do as well, adding a suitable constructor seems not really harm or defeat any purpose, the default i just for the use cases where the application is used at the extension points that can't pass constructor argument easily.

Allow to pass an agent at the constructor for publisher applications

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/Transport.java

Currently the transport only ever knows the URL but that is not enough to make good decisions as it could be a mirror url or the same artifact available from different update-sites.
For this purpose we should offer a new method that allows to pass the repository and the descriptor one want to download from it to the transport so it is possible to make better decisions, especially when the transport supports a native caching mechanism,
This should be backward compatible change of internal class.

Add a way to pass the artifact to be downloaded to the transport

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/RepositoryHelper.java

Provide access to all the PDE bundle pools of all the known workspaces.
https://github.com/eclipse-equinox/p2/issues/410

Support RepositoryHelper.getWorkspaceBundlePools()

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/RepositoryHelper.java

Currently the RepositoryHelper#createMemoryComposite uses the current time millis to generate a "unique" URI, but this has several issues:
Two threads can enter the method at the same time and then see that this "unique" id is currently not taken and then get the same id. It can even happen that both try to create them at the same time, what then will result in a provision exception what will return null and results in no composite created at all.
This do the following to mitigate this:
- uses a UUID instead of timestamp where collisions are already unlikely
- synchronize on the manager for the time of test/create the repository

Synchronize on the manager in RepositoryHelper#createMemoryComposite

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/MirrorRequest.java

Currently there is a NPE if the source repository do not has an agent assigned. Instead of failing, this first tries if the destination has an agent and after that fall back to return null because the IProvisioningEventBus is optional.

Fix possible NPE in MirrorRequestwhen look for IProvisioningEventBus

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/LocalMetadataRepository.java

Currently if one performs an operation as batch and then inside that also performs a batch this resets the save flag even though there are more items to batch in the operation.
This saves the current state and restore that state on completion, save is only performed if saving was not already disabled before.

Save state should be reset to the previous state

---

bundles/org.eclipse.equinox.p2.operations/src/org/eclipse/equinox/p2/operations/RepositoryTracker.java
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/p2/ui/LoadMetadataRepositoryJob.java

Currently it can happen that when the same repository is reported as a problem multiple times then the accumulated status show the same repository multiple times.
This do the following:
1) using a set to record failed URIs
2) check if the URI was failing before
as discovered here:
- https://github.com/eclipse-equinox/p2/pull/343

Do not duplicate failed repository attempts

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/FeatureManifestParser.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeatureEntry.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeaturesAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/FeaturesActionTest.java

Provide new FeatureEntry.createRequires methods that specify isImport, deprecating the older ones, and provide a field as well as accessors for isImport. Use that attribute in FeaturesAction.getFilter(FeatureEntry) to add a filter (!(org.eclipse.equinox.p2.exclude.import=true)) to the synthesized requirement.
Update StringBuffer to StringBuilder in the otherwise-modified files.
https://github.com/eclipse-equinox/p2/issues/138

Add a filter to  requirements corresponding to a feature's imports

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/spi/AbstractArtifactRepository.java

if the location is null then the AbstractArtifactRepository#hashCode throws a NPE because it effectively uses the string representation of the URI.

Fix NPE in AbstractArtifactRepository#hashCode

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/RawMirrorRequest.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/Activator.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/IProvisioningAgent.java

Currently P2 can be controlled by a set of properties that mostly delegate to the Bundle Properties (what effectively is backed by system properties). In certain situations it would be more suitable that the IProvisioningAgent can control these (e.g. max threads, mirrors used or not, checksums enabled, ...).
This adds new (default implemented) methods to IProvisioningAgent to query it for a property where the default simply uses the Bundle properties if available or system properties in all other cases.

Support properties supplied by an agent

---

bundles/org.eclipse.equinox.p2.director/src/org/eclipse/equinox/internal/p2/director/Projector.java

Currently the Projector has no way to influence what requirements/units are considered.
This makes some of the methods protected that are used to take a decision to allow customizing how the projector handles certain things.

Make Projector extensible

---

bundles/org.eclipse.equinox.p2.director/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1744

Touch bundle affected by compiler implementation change

---

bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/RepositoryStatusHelper.java

The httpclientjava implementation can throw an ExecutionException, e.g., when jdk.internal.net.http.Http2Connection.handleGoAway(GoAwayFrame) is called.  This should be unwound so that a retry will be attempted.

Unwind ExecutionException when testing for retry exceptions

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/IProductDescriptor.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/EquinoxExecutableAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeaturesAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeaturesAndBundlesPublisherApplication.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src_ant/org/eclipse/equinox/internal/p2/publisher/ant/AbstractPublishTask.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/BundlesActionTest.java

Currently it is quite cumbersome effort to include the source of a bundle with an installation even though there might be multiple demands, for example legal reasons or debugging.
This now adds a new greedy, optional requirement that is disabled by a filter so it is not effective by default but enables an install agent to specify a property of `org.eclipse.equinox.p2.includesource=true` to include sources of bundles in products whenever available.

Add optional, greedy and disabled by default requirement to the source

---

.gitignore
.mvn/maven.config
bundles/org.eclipse.equinox.p2.tests/pom.xml
examples/pom.xml
pom.xml

Currently the project is configured to use the org.eclipse.equinox.p2 group id but it is actually published to org.eclipse.platform. That is both confusing and makes the metadata in p2 pointless and not allows to use local build artifacts (e.g. for Tycho).
This changes the group id and configures the update-consumer-pom to create a pom that can be used in a local maven setup similar to one published on maven central.
This is what is generated by Tycho for example:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>org.eclipse.platform</groupId> …
```

Adjust maven metadata to the ones actually published to central

---

bundles/org.eclipse.equinox.simpleconfigurator/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.simpleconfigurator/src/org/eclipse/equinox/internal/simpleconfigurator/Activator.java
bundles/org.eclipse.equinox.simpleconfigurator/src/org/eclipse/equinox/internal/simpleconfigurator/ConfigApplier.java
bundles/org.eclipse.equinox.simpleconfigurator/src/org/eclipse/equinox/internal/simpleconfigurator/ResolutionReportListener.java

When refreshing large sets of bundles the resolver sometimes take a choice where a requirement can't be bound even though it is there and resolvable.
This adds some additional code to detect this situation and then refresh a smaller set of bundles that provide these until a max retry is reached, all bundles are resolved, or all providers have been tried to refresh already.

Refresh a subset of bundles if they provide missing requirements

---

bundles/org.eclipse.equinox.p2.engine/.settings/.api_filters
bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/DebugHelper.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Engine.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/EngineActivator.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/PhaseSet.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SimpleProfileRegistry.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/AuthorityChecker.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/CertificateChecker.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/PhaseSetFactory.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/PhaseSetTest.java

Now that agent properties are possible we should use them in the engine, to not rely on only static OSGi context properties.

Migrate p2 engine to agent properties

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ProvidedCapability.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/JREAction.java

in the context of Tycho it could easily happen that there are hundred of
thousands of ProvidedCapability's. Each of them currently carry a
HashMap that is then wrapped in an unmodifiable collection.
This replaces it with Map.copyOf(...) now to ensure it is unmodifiable
and only ever contains the exact number of entries saving a few bytes
for object references and possible null table entries.

Use copy in provided cap

---

bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/TarFile.java

finalize() not needed - only used as autoclosable.

TarFile: fix deprecated finalize()

---

bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/JREAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/JREActionTest.java

Don't hard code "default" JRE version if we "guess one" and create some profile based on current JRE packages. 
Just read & use the version from the running JRE.
Fixes https://github.com/eclipse-equinox/p2/issues/461

UpdateSitePublisher -addJREIU argument doesn't add current JVM

---

.mvn/jvm.config

Fixes https://github.com/eclipse-equinox/p2/issues/463

Workaround for Jenkins builds failing with "Java heap space" errors

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/FeaturesAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/AbstractProvisioningTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/FeaturesActionTest.java

Currently the FeaturesAction assumes that the unpack attribute is always set, if that is not the case it leads to unexpected results because then unpack=true is assumed always. This is especially dangerous as PDE since 2023-12 release removes the attributes and Tycho assume they are false by default the same as PDE has done in the past when adding new items.
To mitigate this this adds an additional check to only evaluate the unpack if it is set, together with a testcase that covers all possible combinations.
I give +1 as project lead for this really late fix but I think it is urgent enough as it has unexpected side-effects for users using already released PDE that will likely be hard to discover and the previous state was to always specify this attribute so existing setup won't be …

Absence of an unpack attribute must not result in BundleShapeAdvice

---

bundles/org.eclipse.equinox.frameworkadmin.equinox/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.frameworkadmin.equinox/src/org/eclipse/equinox/internal/frameworkadmin/equinox/EclipseLauncherParser.java
bundles/org.eclipse.equinox.frameworkadmin.equinox/src/org/eclipse/equinox/internal/frameworkadmin/equinox/utils/FileUtils.java
features/org.eclipse.equinox.p2.core.feature/feature.xml
features/org.eclipse.equinox.p2.extras.feature/feature.xml
features/org.eclipse.equinox.p2.rcp.feature/feature.xml
features/org.eclipse.equinox.p2.sdk/feature.xml
features/org.eclipse.equinox.p2.user.ui/feature.xml
features/org.eclipse.equinox.server.p2/feature.xml

The native launcher executable reads the product *.ini, e.g., eclipse.ini, using the native system encoding. Currently the *.ini is loaded and saved in the launched Java application using the system default encoding, but in Java 21 the default encoding is always UTF-8 so we need to be more careful to always use the native encoding regardless of the default encoding.

Ensure the product *.ini is loaded and saved using the native encoding

---

bundles/org.eclipse.equinox.p2.director.app/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/DirectorApplication.java
bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/Messages.java
bundles/org.eclipse.equinox.p2.director.app/src/org/eclipse/equinox/internal/p2/director/app/messages.properties
bundles/org.eclipse.equinox.p2.publisher/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/JREAction.java

P2 Director Application fails to install some of the bundles which has requirements on Java-SE 21. The reason for this issue was missing java profile dependency during installation. This new option includes Jre IU as an extra installable Unit.
Fixes https://github.com/eclipse-equinox/p2/issues/484

Enhance p2 director with "addJREIU" option.

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

Adjustments corresponding to https://github.com/eclipse-equinox/equinox/pull/564.

Adapt to equinox.security.win32 renaming and adjust arch requirements

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/RawMirrorRequest.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/messages.properties
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java

Currently the message only mentions the artifact to download but not where it originates from, this makes it very hard to analyze and fix the issue (actually one needs to to run a debugger).
This enhances the message a tiny little bit to mention the artifact descriptors repository URL.

Improve warning message with no digest found

---

bundles/org.eclipse.equinox.simpleconfigurator/META-INF/MANIFEST.MF

This was introduced due to a bug in PDE where the auto-mated suggestion unintentionally made the upper-bound inclusive.
See https://github.com/eclipse-pde/eclipse.pde/pull/1212

Fix version-ranges to have exclusive upper-bounds

---

bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/AbstractApplication.java

Fixes warning in I-build https://download.eclipse.org/eclipse/downloads/drops4/I20240404-1800/compilelogs/plugins/org.eclipse.equinox.p2.repository.tools_2.4.400.v20240321-1450/@dot.html#OTHER_WARNINGS

Stop using deprecated IArtifactRepository.removeAll()

---

bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/DiscoveryRegistryStrategy.java

Jars are stored in a list and closed altogether at the end. Fixes https://download.eclipse.org/eclipse/downloads/drops4/I20240416-1800/compilelogs/plugins/org.eclipse.equinox.p2.discovery.compatibility_1.3.300.v20240321-1450/@dot.html#OTHER_WARNINGS

Suppress try-with-resources warning

---

bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/InstallableUnitPhase.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/Collect.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/Sizing.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/touchpoint/eclipse/CollectActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/touchpoint/natives/CollectActionTest.java
bundles/org.eclipse.equinox.p2.touchpoint.natives/src/org/eclipse/equinox/internal/p2/touchpoint/natives/actions/ActionConstants.java
bundles/org.eclipse.equinox.p2.touchpoint.natives/src/org/eclipse/equinox/internal/p2/touchpoint/natives/actions/CollectAction.java

Currently CollectAction and Collect (Phase) both use a parameter 'artifactRequests' but both define them separately.
This unify the access to the constant and modernize the CollectAction to use collections instead of raw arrays.

Unify Constants and modernize CollectAction

---

bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/DownloadManager.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Messages.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/messages.properties
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/Collect.java

There are rare cases where one gets a message that an artifact can not be downloaded from any repository, this has two pitfalls:
1) You don't get an idea what repositories are actually contacted 2) Its hard to find out who actually requires this artifact
This now enhances an IArtifactRequest by a method to set a "context iu" why this artifact is requested. If the information is given, it searches through the available IUs and gives additional information why it is required and what repositories are queried.

Improve message if artifact can not be downloaded from any repository

---

bundles/org.eclipse.equinox.simpleconfigurator/src/org/eclipse/equinox/internal/simpleconfigurator/ConfigApplier.java

Currently there are two ways to refresh packages, one using the deprecated PackageAdmin and one using the FrameworkWiring.
This do the following:
- always use FrameworkWiring
- use collections over arrays
- remove some redundant checks and copy of collections

Do not use PackageAdmin for refresh bundles

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/BundlesActionTest.java
bundles/org.eclipse.equinox.p2.tests/testData/requireMultiple/META-INF/MANIFEST.MF

Currently the BundlesAction uses either 0 or 1 as the cardinality but actually a requirement can be a multi-cardinality as well.
This adds new dedicated methods to not duplicate the computation and a testcase that ensures all combination are covered and correctly translated.

Correctly consider cardinality based on the directives

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductAction.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/AbstractPublisherAction.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/IVersionRangeAdvice.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/actions/RootIUAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ProductActionTest.java

Currently the (disabled by default) requirement for a root feature uses an exact version range when the feature version is expanded (e.g. Tycho) but the purpose of a root feature is that it can be updated what such a strict range makes it impossible (if activated).
This now adds a new IVersionRangeAdvice that allows to modify the result of a product included requirements version range.

VersionRange for root features is too tight when expanded version given

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/spi/AbstractRepository.java

Currently in a debug session it is quite annoying as repositories usually have only the default string what is not really helpful.
This adds a AbstractRepository#toString to print the name and URI if available.

Add AbstractRepository#toString

---

bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/LocalMetadataRepository.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/AbstractRepositoryManager.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/provisional/p2/repository/RepositoryEvent.java
bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/touchpoint/eclipse/actions/RepositoryAction.java
bundles/org.eclipse.equinox.p2.ui/.settings/.api_filters
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/model/ElementUtils.java

Currently there is a quite surprising behavior, that if a user adds an
updatesite that contains a referenced repository, that after an
update-check additional repositories are visible. Even worse these are
now used additionally to check for updates and if they contain other
references these are also added and so on. This can result not only in a
long list of sites the user never has added and has no clue where they
are coming from but even pulling in unwanted or conflicting updates.
Here is an example with the m2e update site (`https://download.eclipse.org/technology/m2e/snapshots/latest/`):
In the first step there is only this single site:
Now I go to `Help > Check For Updates` and after this completes I end up with the following list (**10 sites**):
Now I repeat and perform `Help > …

Remember referenced repositories as system repositories instead of user

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/pde/internal/publishing/Utils.java

Fixes https://github.com/eclipse-pde/eclipse.pde/issues/1272

Don't fail with NPE on non existing manifest

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/EquinoxExecutableAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/EquinoxExecutableActionTest.java

For for Mac OS X there was no equinox-launcher fragment for CARBON with full name, i.e. with <ws>.<os>.<arch> suffix, but only a org.eclipse.equinox.launcher.carbon.macosx fragment. But since Eclipse 4.2, released 2012, CARBON is not supported anymore at all [1]. Therefore the code adjust to that special naming schema, which also imposed difficulties or new supported architectures on Macos should be removed.
See also https://github.com/eclipse-equinox/equinox/pull/622
[1] - https://download.eclipse.org/eclipse/updates/4.2/R-4.2-201206081400

Always use full-named o.e.equinox.launcher artifact

---

bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/metadata/repository/SPIMetadataRepositoryTest.java
bundles/org.eclipse.equinox.p2.ui.discovery/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.discovery/src/org/eclipse/equinox/internal/p2/ui/discovery/util/ControlListViewer.java
bundles/org.eclipse.equinox.p2.ui.importexport/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.importexport/src/org/eclipse/equinox/internal/p2/importexport/internal/wizard/ExportWizard.java
features/org.eclipse.equinox.p2.discovery.feature/feature.xml
features/org.eclipse.equinox.p2.user.ui/feature.xml

When https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2471 is merged, ecj will signal more casts as unnecessary.
With this PR I suggest to remove affected casts before new warnings will show up in the build.

remove unnecessary casts

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/helpers/TarInputStream.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/ReducedCUDFParser.java
bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/UpdateManagerCompatibility.java
bundles/org.eclipse.equinox.simpleconfigurator.manipulator/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.simpleconfigurator.manipulator/src/org/eclipse/equinox/internal/simpleconfigurator/manipulator/SimpleConfiguratorManipulatorUtils.java
features/org.eclipse.equinox.p2.core.feature/feature.xml
features/org.eclipse.equinox.p2.rcp.feature/feature.xml

Avoids NON-NLS and possible UnsupportedEncodingException

Replace "UTF8" with StandardCharsets.UTF_8

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

- There's no reason to lock in a specific version via the feature.

Remove org.tukaani.xz from org.eclipse.equinox.p2.core.feature

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/BrandingIron.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/IProductDescriptor.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/InfoPListEditor.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/MacOsBundleUrlType.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/internal/p2/publisher/eclipse/ProductFile.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/EquinoxExecutableAction.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/IBrandingAdvice.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/IMacOsBundleUrlType.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/ProductFileAdvice.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/EquinoxExecutableActionTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ProductFileAdviceTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/ProductFileTest.java
bundles/org.eclipse.equinox.p2.tests/testData/ProductActionTest/productFileActionTest.product
bundles/org.eclipse.equinox.p2.tests/testData/ProductActionTest/productWithMacOsBundleUrlTypes.product

Adds CFBundleURLTypes entries to the Info.plist dictionary.
Contributes to
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901.

Add support for bundle URL types in macOS launcher in product files

---

bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/DownloadManager.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/p2/engine/ProvisioningContext.java

https://github.com/eclipse-platform/eclipse.platform.ui/issues/2265

Ensure that a jar:file: URI is considered local for artifact requests

---

Jenkinsfile

and other minor clean-ups of the Jenkinsfile.
Remove explicit declaration of properties that are already defined in the `eclipse-platform-parent/pom.xml` or that are not considered by any plugin (i.e. `maven.test.error.ignore`).

[Build] Fix archiving of log files in Jenkins pipeline

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/p2/metadata/VersionRange.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/omniVersion/OSGiRangeTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/omniVersion/RawRangeTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/omniVersion/VersionTesting.java

This enables support for version range specifications where the lower or upper bound is not specified and the delimiting bracket is directly next to the separating colon. For example `[1,)` or `(,1]` but also `(,)` can then be parsed successfully.
The type of supported brackets for an empty or unspecified bound is something that's not inherently obvious. From a mathematical perspective an empty bound can be considered equivalent to infinity. And in math may not say inclusive infinity. From that perspective only `[1,infinity)` respectively `[1,)` would be permitted, but not `[1,]`. But technically infinity has a specific value for P2 versions, i.e. `Version.MAX_VERSION`. So if one really wants to cover all possible values, the upper bound still has to be inclusive, i.e. `]`. For the lower …

Support empty lower and upper bounds in P2 VersionRange

---

bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/SiteXMLAction.java
bundles/org.eclipse.equinox.p2.updatesite/src/org/eclipse/equinox/internal/p2/updatesite/artifact/UpdateSiteArtifactRepositoryFactory.java

Generification and deprecated usages.

Fix warnings in o.e.e.p2.updatesite

---

pom.xml

As suggested in https://github.com/eclipse-equinox/p2/pull/573, this applies the changes necessary for release preparation manually, that cannot be done automatically at the moment due to a bug in Tycho. See
- https://github.com/eclipse-tycho/tycho/pull/3900#issuecomment-2495468974

Update for release 4.35

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.publisher/forceQualifierUpdate.txt
features/org.eclipse.equinox.p2.extras.feature/feature.xml
features/org.eclipse.equinox.p2.sdk/feature.xml
features/org.eclipse.equinox.p2.user.ui/feature.xml

Changes to ecj are for handling of switch on String.
See: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2595

Updated bundles with comparator errors

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/IProvisioningAgent.java
bundles/org.eclipse.equinox.p2.engine/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Messages.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/messages.properties
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/AuthorityChecker.java
bundles/org.eclipse.equinox.p2.ui.sdk/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.sdk/src/org/eclipse/equinox/internal/p2/ui/sdk/TrustPreferencePage.java
features/org.eclipse.equinox.p2.core.feature/feature.xml
features/org.eclipse.equinox.p2.discovery.feature/feature.xml
features/org.eclipse.equinox.p2.rcp.feature/feature.xml
features/org.eclipse.equinox.server.p2/feature.xml

As explained in #567, it is currently possible that Eclipse waits infinitely for a host certificate in case the server accepting the request but not responding after that. This issue [caused the plugin installation of a Stack Overflow user to get stuck](https://stackoverflow.com/q/79193830/10871900).
This PR adds a timeout and retrying using the properties `org.eclipse.equinox.p2.engine.requestTimeout` and `org.eclipse.equinox.p2.engine.requestRetries`.
- Create a server that accepts incoming connections but never responds, e.g. `nc -l 8080 -k` on Linux or using Java code similar to the following (not using TLS for simplicity):
```java
try(ServerSocket servSock = new ServerSocket(8080)){
while(true){
try(Socket sock = servSock.accept();
BufferedReader br = new BufferedReader(new …
```

Add timeout to gathering host certificates #567

---

bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/DownloadJob.java
bundles/org.eclipse.equinox.p2.discovery.compatibility/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/BundleDiscoveryStrategy.java
bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/RemoteBundleDiscoveryStrategy.java
bundles/org.eclipse.equinox.p2.discovery/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.discovery/src/org/eclipse/equinox/internal/p2/discovery/Catalog.java
bundles/org.eclipse.equinox.p2.transport.ecf/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileReader.java
bundles/org.eclipse.equinox.p2.ui/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/query/QueryableUpdates.java

From the documentation:
> Since it is illegal to call beginTask on the same IProgressMonitor
> more than once, the same instance of IProgressMonitor must not be
> passed to convert more than once.
The proper way is to replace calls to IProgressMonitor.beginTask(...) with SubMonitor.convert(...), keep the SubMonitor as a local variable and use that from now on.
This amends commit 9009085b72e9507fdc4b7d0adb87883adefc5637.

Correct improper usage of the SubMonitor

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/CompositeArtifactRepository.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/CompositeArtifactRepositoryFactory.java

See https://www.eclipse.org/articles/Article-Progress-Monitors/article.html

Remove unnecessary done() call on ProgressMonitor

---

bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/DownloadManager.java

See https://www.eclipse.org/articles/Article-Progress-Monitors/article.html

DownloadManager - remove unnecessary done() call on ProgressMonitor

---

bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/planner/TychoUsage.java

As can be seen at
https://download.eclipse.org/eclipse/downloads/drops4/I20241218-0910/testresults/html/org.eclipse.equinox.p2.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html :
Unable to read repository at
https://download.eclipse.org/releases/2021-09.
* Move to 2024-12 to reduce potential slowness if 2021-09 comes from archive.eclipse.org
* Remove useless sysouts of currentTimeMillis
* Extract version/urls to constants for easier editing in the future

TychoUsage.testTychoUsage failed in I20241218-0910

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/Messages.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/messages.properties
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/DownloadJob.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/CompositeArtifactRepositoryTest.java

Currently the reporting of progress for download jobs has some flaws:
1) it concurrently updates a shared monitor but these are usually not made for concurrent use
2) the jobs own monitor does not really reflect progress 3) Messages are not externalized
This now refactor this part in the following way:
- create a submonitor from the job so we can update the remaning work
- assign some subticks to each download to report progress on the job
- set the current artifact behind downloaded as the message
- report messages from downstream as sub task to the job
- add two consumers for the caller of the job to get notified about messages and status

Improve progress reporting for download jobs

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/RawMirrorRequest.java

Currently RawMirrorRequest can fail if no repository is given in the descriptor and it want to log a message.
P2 should be gracefully in this case and simply report the location as being unknown.

Prevent NPE when no artifact repository is given

---

features/org.eclipse.equinox.p2.core.feature/feature.xml
products/org.eclipse.equinox.p2.examples.rcp.discovery.product/cloud.product
products/org.eclipse.equinox.p2.examples.rcp.prestartupdate.product/prestartupdate.product
products/org.eclipse.equinox.p2.examples.rcp.sdkbundlevisibility.product/sdkbundlevisibility.product
products/org.eclipse.equinox.p2.examples.rcp.sdknoautoupdates.product/sdknoautoupdates.product
products/org.eclipse.equinox.p2.examples.rcp.sdkui.product/sdkui.product
products/org.eclipse.equinox.p2.installer.product/installer.product
products/org.eclipse.equinox.p2.ui.admin.rcp.product/rcp.product

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2725

Remove references to all of ECF's ssl bundles and features

---

bundles/org.eclipse.equinox.p2.core/.settings/.api_filters
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/EventBusComponent.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/ProvisioningAgent.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/spi/IAgentServiceFactory.java
bundles/org.eclipse.equinox.p2.tests.ui/META-INF/MANIFEST.MF

Currently we use the property `p2.agent.servicename` to identify the provided service, but the constant is named `PROP_CREATED_SERVICE_NAME`. So beside the inconsistency of created <> agent it shows that the "name" part should actually be an own segment (like in AgentServiceFactory). This also affects the naming of component property types
Because of this we introduce here a new constant `PROP_AGENT_SERVICE_NAME` with the value 'p2.agent.service.name' and deprecate the old constant while remain support for both properties.

Migration to more consistent property name for provided service

---

bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/internal/p2/core/EventBusComponent.java
bundles/org.eclipse.equinox.p2.core/src/org/eclipse/equinox/p2/core/spi/AgentServiceName.java

Component property types are much more expressive and convenient to use than string concatenations and less error prone on refactorings/reference searches.
This now adds a new component property type for the `p2.agent.service.name` and uses it at the place where it previously using the property constant to show usage.
I also checked for the case now that it produces the same component.xml output

Add component property type for agent service name property

---

bundles/org.eclipse.equinox.p2.artifact.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.artifact.repository/OSGI-INF/org.eclipse.equinox.internal.p2.artifact.repository.DefaultArtifactManagerServiceFactory.xml
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/ArtifactManager.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/DefaultArtifactManagerServiceFactory.java
bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/SimpleArtifactRepository.java

Caching can greatly improve performance, basically P2 has two concepts of where caching can occur, the transport and artifacts that can originate from different sources. Currently there is only a CacheManger for handling the first case and nothing for the second, maybe even more important case. Because of this there are different approaches out in the wild e.g. PDE Bundle Pools, Oomph shared P2 pools, and Tycho is using its own cache in the m2 repository, but all of them suffer from the fact that there is no real convenient entry point so different things needs to be enhanced an managed.
This now adds a new abstraction service the ArtifactManager that allows to intercept the process of downloading a logical artifact from a given location and possibly providing an equivalent one that is …

Add an ArtifactManager to allows unified managing of artifacts

---

bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java

Currently FileInfoReader has some public methods even though no one use them anywhere, also a protected field that is only used internally and a method that is never called.
To make refactroing easier and the code more hiding its internal details, this now reduce visibility as much as possible and remove unused methods.

Reduce visibility and remove unused methods from FileInfoReader

---

bundles/org.eclipse.equinox.p2.transport.ecf/src/org/eclipse/equinox/internal/p2/transport/ecf/FileInfoReader.java

The FileInfoReader currently creates a job just to join its execution, as the job is also marked as a system job to hide it from the users this does not seem very useful and only complicates the flow and increased the workload.
This now removes the job extension and also making the monitor field obsolete now.

Do not use a job in the FileInfoReader

---

bundles/org.eclipse.equinox.p2.ui.discovery/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.ui.discovery/src/org/eclipse/equinox/internal/p2/ui/discovery/util/PatternFilter.java

Update lower bound to org.eclipse.core.runtime in ui.discovery due to

---

bundles/org.eclipse.equinox.p2.core/META-INF/MANIFEST.MF

There was a version bump missing for the core+spi packages due to changed API, beside that I removed the import of these packages here there was once an idea to make it possible to substitute this package in Tycho but this actually never happend, on the long run we better would have a dedicated API bundle instead.

Add missing version bump of packages and remove import

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ProvidedCapability.java
bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/publisher/actions/BundlesActionTest.java
bundles/org.eclipse.equinox.p2.tests/testData/pkgAttributes/META-INF/MANIFEST.MF

Currently P2 lacks support for package attributes and directives that can lead to wrong selection of providers. One issue is that the information on exported packages are not recorded at all in the P2 metadata and therefore can not be used in slicer or planner operations.
As a first step this now records the information on the provider side by transforming attributes and directives into properties of the package capability.

Record Package Attributes and Directives on exported packages

---

pom.xml

Don't redefine the `releaseVersion` from the `eclipse-platform-parent/pom.xml` with a slightly different value.
This reduces the number of required changes in the preparation of new release-cycles and unblocks
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2799

[Build] Reuse 'releaseVersion' property from eclipse-platform-parent

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/src/org/eclipse/equinox/p2/publisher/eclipse/BundlesAction.java

It is often useful to get some information about a file and BundlesAction is the P2 way to gather such data, but at the moment it is really cumbersome and requires a lot of calls and handling of cases to get to that point.
This now adds a new method BundlesAction.createBundleIU(File) that ease this task.

Add BundlesAction.createBundleIU(File) for easy creation of IU

---

bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/spi/AbstractRepository.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/artifact/repository/MirrorRequestTest2.java

- Make AbstractRepository.properties final.
- Modify AbstractRepository.setProperties to do a clear and a putAll.
- Make the only method that accesses AbstractRepository.properties without synchronization, AbstractRepository.getProperty(String), also be synchronized.
https://github.com/eclipse-tycho/tycho/issues/4709

Ensure that AbstractRepository.properties cannot be replaced

---

bundles/org.eclipse.equinox.p2.ui.sdk.scheduler/src/org/eclipse/equinox/internal/p2/ui/sdk/scheduler/AutomaticUpdatePlugin.java

`AutomaticUpdatePlugin.getSession()` changed to a synchronized method.

Ensure a single instance of the variable *session*.

---

bundles/build.properties
features/build.properties

Relates to
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2950

Ensure unique artifactIds for pomless aggregation modules

---

bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/Messages.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/VersionParser.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/messages.properties

This PR helps debugging when there was an invalid version string passed.
I wasted hours trying to figure out a failing build because an invalid version string was passed in a <plugin> definition of a p2 feature.xml But the Exception unfortunatelly does not tell what the wrong string was.
```
BUILD FAILED
java.lang.IllegalArgumentException
at org.eclipse.equinox.internal.provisional.p2.core.VersionParser.parseInto(VersionParser.java:71)
at org.eclipse.equinox.internal.provisional.p2.core.Version.create(Version.java:138)
at org.eclipse.equinox.internal.provisional.p2.core.Version.parseVersion(Version.java:162)
at org.eclipse.equinox.p2.publisher.eclipse.FeatureEntry.<init>(FeatureEntry.java:51)
at org.eclipse.equinox.internal.p2.publisher.eclipse.FeatureManifestParser.processPlugin(FeatureMa …
```

VersionParser: make Exception message more meaningful

---

bundles/org.eclipse.equinox.p2.publisher.eclipse/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2995

Touch bundles affected by compiler changes

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/simple/BlobStore.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/MetadataRepositoryIO.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/io/MetadataWriter.java
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/UpdateSingleIUPage.java

Calling `new URL(uri.toString()).toExternalForm())` instead of `uri.toString()` does not seem to have a benefit.
And `BlobStore.fileFor()` should return an absolute URI and therefore `URI.toURL()` should be save too.

Simplify URI to string conversion and avoid URIUtil.toURL()

---

bundles/org.eclipse.equinox.p2.touchpoint.natives/nativePackageScripts/windows/isInstalled.bat

- Tests are failing depending on what is on the system PATH environment variable, i.e., the script find the wrong find executable, the one from git bash rather than the windows native find.
- Do the same for `reg`.

Use absolute paths to invoke reg and find

---

bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/engine/SurrogateProfileHandlerTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/AbstractSharedInstallTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/BaseChange.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/BaseChangeExtendedConfigured.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/BaseChangeExtendedConflicts.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/BaseChangeWithoutUserChange.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/Cancellation.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/DoubleBaseChange.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/InitialSharedInstall.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/InitialSharedInstallRealTest.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/InstallInUserSpace.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/MultipleChanges.java
bundles/org.eclipse.equinox.p2.tests/src/org/eclipse/equinox/p2/tests/sharedinstall/TestInitialRun.java

Failure messages, and I quote, `oh shit` are not really helpful.
Hopefully this helps to identify why some P2 tests are currently failing.

Propagate Exceptions in P2 tests to have more meaningful failures

---

bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/Profile.java
bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java
bundles/org.eclipse.equinox.p2.metadata/src/org/eclipse/equinox/internal/p2/metadata/ProvidedCapability.java
bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/p2/publisher/AbstractPublisherApplication.java

If the message doesn't have params defined calling NLS.bind(message, null) is simply a noop.

Stop using NLS.bind needlessly

---

features/org.eclipse.equinox.p2.core.feature/feature.xml

- Only import the bundles that are not required by any p2 bundle, i.e., the ones that provide the extensions to the underlying framework that are directly required by p2.

Replace ECF feature imports with bundle imports

---

bundles/org.eclipse.equinox.p2.artifact.repository/src/org/eclipse/equinox/internal/p2/artifact/repository/ArtifactRepositoryManager.java
bundles/org.eclipse.equinox.p2.metadata.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/MetadataRepositoryManager.java
bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/AbstractApplication.java
bundles/org.eclipse.equinox.p2.repository.tools/src/org/eclipse/equinox/p2/internal/repository/tools/CompositeRepositoryApplication.java
bundles/org.eclipse.equinox.p2.repository/META-INF/MANIFEST.MF
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/IRepositoryManager.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/artifact/IArtifactRepositoryManager.java
bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/p2/repository/metadata/IMetadataRepositoryManager.java

This simplifies the implementations and makes it easier to discover what default value is used for 'flags'.

Default implement IRepositoryManager.loadRepository(URI, IProgressMonitor)

---

bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/io/MetadataParser.java
bundles/org.eclipse.equinox.p2.metadata.repository/src/org/eclipse/equinox/internal/p2/metadata/repository/io/MetadataWriter.java
bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/TrustAuthorityDialog.java

- The implementation of InstallableUnit.getTouchpointType() always returns a non-null result returning ITouchpointType.NONE when the underlying field InstallableUnit.touchpointType is null so there is no need to serialize this.
- Also MetadataFactory.createTouchpointType(String, Version) has specialized handling for deserliazing ITouchpointType.NONE such that it makes no difference to deserialize the value versus there being no value specified.

Don't serialize ITouchpointType.NONE

---

.github/workflows/doCleanCode.yml

As it worked for Equinox since a while now and P2 also offers a lot of API it seems good to have it enabled here as well.

Enable Manifest cleanups for P2 repository

---

features/org.eclipse.equinox.p2.sdk/feature.properties
features/org.eclipse.equinox.p2.sdk/feature.xml

- The repositories and products that use this SDK feature using includeAllSources to ensure that sources are available.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3206

Remove source features and source bundles from o.e.equinox.p2.sdk

---

pom.xml

- With the removal of the  source features from the SDK feature, this is no longer needed.

Remove tycho-source-plugin's feature-source goal
